### ISSUE TITLE
It is possible to get response through proxy?

### ISSUE THREAD

**Issue by MeterSoft** [sntran/ex_maps#13]

**Comment by sntran** [comment]
Did you mean support the [`:proxy` option](https://github.com/edgurgel/httpoison/blob/64c58d0683aeee3ed1b244893d8780960de99555/lib/httpoison/base.ex#L146) from `httpoison`?

I can add it, just have to figure out the best place to pass it.

**Comment by MeterSoft** [comment]
yes right

**Comment by MeterSoft** [comment]
need ability to enter new proxy to each request

**Comment by sntran** [comment]
I have pushed a commit to support passing `headers` and `options` params. Please test it using `master` branch. When it works, I will deploy a new version to Hex.

See https://github.com/sntran/ex_maps/blob/6c19debde659fb058b87f08de6a91021b95d82cb/lib/google_maps.ex#L1485-L1502 for examples.

**Comment by MeterSoft** [comment]
Proxy not works. Google response error is using https and proxy. For proxy should use http like this
http://maps.googleapis.com/maps/api/geocode/json?address=#{address}

**Comment by sntran** [comment]
Google requires request over SSL if it contains API key, so you would not be able to do a lot through proxy without an API key.

With that said, I have pushed a commit to let you pass the full URL for request, in case you want to use http.

Example:
https://github.com/sntran/ex_maps/blob/0b8c0bfd4ccf1914759fbaa00cf355f07012a11b/lib/google_maps.ex#L1504-L1509

**Comment by MeterSoft** [comment]
In this case it looks like standard request
HTTPoison.get("http://maps.googleapis.com/maps/api/geocode/json?address=#{address}", [], [ecv_timeout: 30000, timeout: 30000, proxy: "#{proxy_data["ip"]}:#{proxy_data["port"]}"])

**Comment by sntran** [comment]
Yes, it's because you are doing at the request level. This library is just a wrapper for simple requests. As you get more specific, you just have to drop back to doing things manually.

Would supporting a `secure` param help in your case? So you only need to do this:

```elixir
GoogleMaps.geocode(address, [
  secure: false, 
  options: [proxy: "#{proxy_data["ip"]}:#{proxy_data["port"]}"]
])
```

**Comment by MeterSoft** [comment]
i think it looks as  better solution

**Comment by sntran** [comment]
@MeterSoft please checkout master branch for the `secure` option

**Comment by sntran** [comment]
I haven't heard from @MeterSoft for a while, so I'll close this issue.
