### ISSUE TITLE
Library config

### ISSUE THREAD

**Issue by lukeses** [sntran/ex_maps#2]
Hi,

What do you think about adding a param with an API key to each public function?

I mean, e.g. `geocode(input, options \\ [], api_key)`.

That way, we can have a more control over API keys used in the application. If someone doesn't provide api_key, an application can fall back to config:
`@api_key Application.get_env(:google_maps, :api_key) || System.get_env("GOOGLE_MAPS_API_KEY")` as it is set in the `GoogleMaps.Request`

**Comment by sntran** [comment]
Hi there,

You can now use `geocode(input, [key: api_key])`.

**Comment by lukeses** [comment]
Thank you @sntran! 👍
